title: It's A Life Blof
author: NuelBali
email: nueldig@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ace of base song with title: It's a beautiful life

# social links
twitter_username: dalansae # DO NOT include the @ character, or else the build will fail!
github_username:  nueldig # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
